package com.levelup.app.data

/**
 * Plain Kotlin model the UI layer talks to. Mirrors the [com.levelup.app.data.db.Mission]
 * row generated by SQLDelight, but keeps the UI free of any DB types.
 */
data class Mission(
    val id: Long = 0,
    val title: String,
    val description: String = "",
    val type: MissionType,
    val stat: StatType,
    val difficulty: Difficulty,
    val xpReward: Int,
    val statReward: Int,
    val parentId: Long? = null,
    val createdAt: Long,
    val completed: Boolean = false,
    val completedAt: Long? = null,
    val archived: Boolean = false,
    val lastCompletedDate: String? = null,
    val currentStreak: Int = 0,
    val bestStreak: Int = 0
)

enum class MissionType { MAIN, SIDE, DAILY }

enum class StatType(val displayName: String, val emoji: String) {
    STRENGTH("Strength", "STR"),
    INTELLIGENCE("Intelligence", "INT"),
    DISCIPLINE("Discipline", "DIS"),
    VITALITY("Vitality", "VIT"),
    SOCIAL("Social", "SOC")
}

enum class Difficulty(val displayName: String, val xp: Int, val statPoints: Int) {
    TRIVIAL("Trivial", 10, 1),
    EASY("Easy", 25, 1),
    NORMAL("Normal", 60, 2),
    HARD("Hard", 140, 3),
    EPIC("Epic", 320, 5),
    LEGENDARY("Legendary", 700, 8)
}

data class Profile(
    val id: Long = 1,
    val hunterName: String = "Hunter",
    val totalXp: Long = 0,
    val strength: Int = 0,
    val intelligence: Int = 0,
    val discipline: Int = 0,
    val vitality: Int = 0,
    val social: Int = 0,
    val lifetimeMissionsCompleted: Int = 0,
    val createdAt: Long
)

data class Completion(
    val id: Long = 0,
    val missionId: Long,
    val missionTitle: String,
    val stat: String,
    val xpAwarded: Int,
    val statAwarded: Int,
    val completedAt: Long
)

data class Achievement(
    val code: String,
    val title: String,
    val description: String,
    val unlockedAt: Long
)
